version: "3.8"

services:
  flaskapp:
    image: python:3.11-slim
    container_name: web2-flaskapp
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./flask-app:/app
    command: >
      sh -c "pip install --no-cache-dir flask &&
             python app.py"
    ports:
      - "8080:5000"
